<?php

declare(strict_types=1);

namespace Ukrposhta\Tests\Utils;

use Faker\Generator;

class FakerGenerator extends Generator implements FakerGeneratorInterface
{
    public function barcode(): string
    {
        return $this->numerify('barcode-#############');
    }

    public function randomDigitOrNull(): ?int
    {
        return random_int(0, 1) === 1 ? $this->randomDigit() : null;
    }

    public function randomStringOrNull(): ?string
    {
        return random_int(0, 1) === 1 ? $this->lexify() : null;
    }

    public function sentenceOrNull(int $length = 3): ?string
    {
        return random_int(0, 1) === 1 ? $this->sentence($length) : null;
    }

    public function uuid(): string
    {
        return parent::uuid();
    }

    public function boolean(): bool
    {
        return parent::boolean();
    }

    public function word(): string
    {
        return parent::word();
    }

    public function words(int $nb = 3, bool $asText = false): array|string
    {
        return parent::words($nb, $asText);
    }

    public function url(): string
    {
        return parent::url();
    }

    public function randomElements(array $array = ['a', 'b', 'c'], int $count = 1, bool $allowDuplicates = false): array
    {
        return parent::randomElements($array, $count, $allowDuplicates);
    }

    public function address(): string
    {
        return parent::address(); // TODO: Change the autogenerated stub
    }

    public function languageCode(): string
    {
        return parent::languageCode(); // TODO: Change the autogenerated stub
    }
}
